Electronics Workbench Extension

$
00782 00116                                          
""
"VBR"
"Forward breakover voltage"
"VS"
"Switching voltage"
"VDRM"
"Forward breakover voltage"
"TQ"
"Turn-off time"
"DV/DT"
"Critical rate of off-state voltage rise"
"IH"
"Holding current"
"VCC"
"Positive power supply"
"VEE"
"Negative power supply"
"CMRR"
"Common mode rejection ratio"
"ISC"
"Output short circuit current"
"VGT"
"Gate trigger voltage"
"IGT"
"Gate trigger current"
"Peak off-state current"
"IDRM"
"Forward voltage at which IGT is measured"
"VD"
"%"
"Setting"
"Increment"
"Peak on-state voltage"
"VTM"
"Forward current at which VTM is measured"
"ITM"
"Phase margin"
"ôM"
"Silicon-Controlled Rectifier"
"Shockley Diode"
"Buzzer"
"Potentiometer"
"Diac"
"Triac"
"Variable Capacitor"
"Full-Wave Bridge Rectifier"
"5-Terminal Opamp"
"555 Timer"
"dB"
"V/us"
"Voltage at which IGT is measured"
"VD"
"Variable Inductor"
"Peak off-state reverse current"
"IREV"
"A polarized capacitor is reverse-biased"
"Multiplier constant"
"K"
"Multiplier"
"Polarized Capacitor"
"Resistor Pack"
"Clock"
"Voltage"
"V"
"Duty cycle"
"D"
"Frequency"
"F"
"Constant"
"A"
"Coefficient of V1"
"B"
"Coefficient of V2"
"C"
"Coefficient of V3"
"D"
"Coefficient of V1²"
"E"
"Coefficient of V1*V2"
"F"
"Coefficient of V1*V3"
"G"
"Coefficient of V2²"
"H"
"Coefficient of V2*V3"
"I"
"Coefficient of V3²"
"J"
"Coefficient of V1*V2*V3"
"K"
"Divider constant"
"K"
"Saturation current"
"IS"
"Series resistance"
"RS"
"Diode capacitance at low reverse voltage point"
"CDL"
"VDL"
"Voltage at which the above capacitance is measured"
"CDH"
"Diode capacitance at high reverse voltage point"
"VDH"
"Voltage at which the above capacitance is measured"
"VR"
"Maximum continuous reverse voltage"
"LEN"
"Length of the transmission line"
"N"
"Number of lumps"
"R"
"Resistance per unit length"
"L"
"Inductance per unit length"
"C"
"Capacitance per unit length"
"G"
"Conductance per unit length"
"Z0"
"Nominal impedance"
"TD"
"Propogation time delay"
"VF"
"Forward voltage drop"
"IF"
"Current at which VF is measured"
"ION"
"Turn-on current"
"VH"
"Highest segment turn-on voltage"
"VL"
"Lowest segment turn-on voltage"
"VC"
"Carrier amplitude"
"FC"
"Carrier frequency"
"M"
"Modulation index"
"FM"
"Modulation frequency"
"VA"
"Peak amplitude"
"FC"
"Carrier frequency"
"M"
"Modulation index"
"FM"
"Modulation frequency"
"Lossy Transmission Line"
"Lossless Transmission Line"
"Bargraph Display"
"Decoded Bargraph Display"
"Number of lumps should be a power of 2 and less than 128"
"Divider"
"AM Source"
"FM Source"
"Polynomial Source"
"Ideal DC Motor"
"Piecewise Linear Source"
"Crystal"
"Motional inductance"
"LS"
"Motional capacitance"
"CS"
"Series resistance"
"RS"
"Shunt capacitance"
"CO"
"Frequency-Shift-Keying Source"
"Pulse Width Modulating Source"
"Select input file"
"Accept"
"Text only (*.TXT)|*.txt|Scope Data (*.SCP)|*.scp|"
"No input file"
"Mark transmission frequency"
"F1"
"Space transmission frequency"
"F2"
"Peak amplitude of FSK signal"
"A"
"Maximum value of the modulating voltage"
"VMAX"
"Minimum value of the modulating voltage"
"VMIN"
"Amplitude of the PWM wave"
"VPWM"
"Minimum duty cycle of the PWM"
"DTMIN"
"Maximum duty cycle of the PWM"
"DTMAX"
"Frequency"
"F"
"Input offset voltage"
"VIOFF"
"Output offset voltage"
"VOOFF"
"Gain"
"K"
"Output voltage lower limit"
"VL"
"Output voltage upper limit"
"VU"
"Upper and lower limit smoothing range"
"VS"
"Input C offset voltage"
"Input A offset voltage"
"Input B offset voltage"
"VCOFF"
"VAOFF"
"VBOFF"
"Input C gain"
"KC"
"Input A gain"
"KA"
"Input B gain"
"KB"
"Output gain"
"KOUT"
"Output initial conditions"
"VOIC"
"Numerator constant"
"A0"
"Numerator 1st order coefficient"
"A1"
"Numerator 2nd order coefficient"
"A2"
"Numerator 3rd order coefficient"
"A3"
"Denominator constant"
"B0"
"Denominator 1st order coefficient"
"B1"
"Denominator 2nd order coefficient"
"B2"
"Denominator 3rd order coefficient"
"B3"
"Integrator stage initial conditions"
"VINT"
"Denormalized corner frequency"
"W"
"Voltage Gain Block"
"Voltage Limiter"
"Three-Way Voltage Summer"
"Voltage Differentiator"
"Voltage Integrator"
"Transfer Function Block"
"DC Motor"
"Rated power"
"P"
"Rated rotational speed"
"NN"
"Machine rotational inertia"
"J"
"Armature inductance"
"LA"
"Shaft friction"
"BF"
"Armature resistance"
"RA"
"Rated armature voltage"
"VAN"
"Voltage-Controlled Oscillator"
"Output voltage amplitude"
"A"
"Center frequency"
"FC"
"Voltage-to-frequency gain"
"KC"
"Minimum VCO frequency"
"FMIN"
"Voltage-Controlled Piecewise Linear Source"
"Number of co-ordinates"
"N"
"X co-ordinate 1"
"X1"
"Y co-ordinate 1"
"Y1"
"X co-ordinate 2"
"X2"
"Y co-ordinate 2"
"Y2"
"X co-ordinate 3"
"X3"
"Y co-ordinate 3"
"Y3"
"X co-ordinate 4"
"X4"
"Y co-ordinate 4"
"Y4"
"X co-ordinate 5"
"X5"
"Y co-ordinate 5"
"Y5"
"Input smoothing domain %"
"ISD"
"Zener Diode"
"Breakdown voltage"
"VBR"
"Breakdown current"
"IBR"
"Saturation current"
"ISAT"
"Forward emission coefficient"
"N"
"Coreless Coil"
"Number of inductor turns"
"N"
"Voltage Inductance Meter"
"Gain"
"K"
"Voltage Capacitance Meter"
"Gain"
"K"
"Multiplier"
"Output gain"
"K"
"Output offset"
"OFF"
"Y offset"
"YOFF"
"Y gain"
"YK"
"X offset"
"XOFF"
"X gain"
"XK"
"Divider"
"Output gain"
"K"
"Output offset"
"OFF"
"Y (numerator) offset"
"YOFF"
"Y (numerator) gain"
"YK"
"X (denominator) offset"
"XOFF"
"X (denominator) gain"
"XK"
"X (denominator) lower limit"
"XLOWLIM"
"X (denominator) smoothing domain"
"XSD"
"Magnetic Core"
"Cross-sectional area"
"A"
"Core length"
"L"
"Number of co-ordinates"
"N"
"Magnetic field co-ordinate 1"
"H1"
"Flux density co-ordinate 1"
"B1"
"Magnetic field co-ordinate 2"
"H2"
"Flux density co-ordinate 2"
"B2"
"Magnetic field co-ordinate 3"
"H3"
"Flux density co-ordinate 3"
"B3"
"Magnetic field co-ordinate 4"
"H4"
"Flux density co-ordinate 4"
"B4"
"Magnetic field co-ordinate 5"
"H5"
"Flux density co-ordinate 5"
"B5"
"Input smoothing domain %"
"ISD"
"Controlled One-Shot"
"Clock trigger value"
"CLKTR"
"Output low value"
"L"
"Output high value"
"H"
"Output delay from trigger"
"DTR"
"Output rise time"
"TR"
"Output fall time"
"TF"
"Number of co-ordinates"
"N"
"Control co-ordinate 1"
"C1"
"Pulse width co-ordinate 1"
"PW1"
"Control co-ordinate 2"
"C2"
"Pulse width co-ordinate 2"
"PW2"
"Control co-ordinate 3"
"C3"
"Pulse width co-ordinate 3"
"PW3"
"Control co-ordinate 4"
"C4"
"Pulse width co-ordinate 4"
"PW4"
"Voltage-Controlled Sine Wave Oscillator"
"Output peak low value"
"L"
"Output peak high value"
"H"
"Number of co-ordinates"
"N"
"Control co-ordinate 1"
"C1"
"Frequency co-ordinate 1"
"F1"
"Control co-ordinate 2"
"C2"
"Frequency co-ordinate 2"
"F2"
"Control co-ordinate 3"
"C3"
"Frequency co-ordinate 3"
"F3"
"Control co-ordinate 4"
"C4"
"Frequency co-ordinate 4"
"F4"
"Control co-ordinate 5"
"C5"
"Frequency co-ordinate 5"
"F5"
"Voltage-Controlled Square Wave Oscillator"
"Output peak low value"
"L"
"Output peak high value"
"H"
"Duty cycle"
"D"
"Output rise time"
"TR"
"Output fall time"
"TF"
"Number of co-ordinates"
"N"
"Control co-ordinate 1"
"C1"
"Frequency co-ordinate 1"
"F1"
"Control co-ordinate 2"
"C2"
"Frequency co-ordinate 2"
"F2"
"Control co-ordinate 3"
"C3"
"Frequency co-ordinate 3"
"F3"
"Control co-ordinate 4"
"C4"
"Frequency co-ordinate 4"
"F4"
"Control co-ordinate 5"
"C5"
"Frequency co-ordinate 5"
"F5"
"Voltage-Controlled Triangle Wave Oscillator"
"Output peak low value"
"L"
"Output peak high value"
"H"
"Rise time duty cycle"
"RTD"
"Number of co-ordinates"
"N"
"Control co-ordinate 1"
"C1"
"Frequency co-ordinate 1"
"F1"
"Control co-ordinate 2"
"C2"
"Frequency co-ordinate 2"
"F2"
"Control co-ordinate 3"
"C3"
"Frequency co-ordinate 3"
"F3"
"Control co-ordinate 4"
"C4"
"Frequency co-ordinate 4"
"F4"
"Control co-ordinate 5"
"C5"
"Frequency co-ordinate 5"
"F5"
"Current Limiter Block"
"Input offset"
"OFF"
"Gain"
"K"
"Sourcing resistance"
"RSRC"
"Sinking resistance"
"RSINK"
"Current sourcing limit"
"ISRCL"
"Current sinking limit"
"ISNKL"
"Upper and lower power supply smoothing range"
"ULSR"
"Sourcing current smoothing range"
"ISRCSR"
"Sinking current smoothing range"
"ISNKSR"
"Internal/external voltage delta smoothing range"
"VDSR"
"Voltage Hysteresis Block"
"Input low value"
"VIL"
"Input high value"
"VIH"
"Hysteresis"
"H"
"Output lower limit"
"VOL"
"Output upper limit"
"VOH"
"Input smoothing domain %"
"ISD"
"Voltage Slew Rate Block"
"Maximum rising slope value"
"RSMAX"
"Maximum falling slope value"
"FSMAX"
"Smoothing range"
"SR"
"Voltage-Controlled Analog Switch"
"Control 'off' value"
"COFF"
"Control 'on' value"
"CON"
"Off resistance"
"ROFF"
"On resistance"
"RON"
"Output delay from pulse width"
"DPW"
"Voltage-Controlled Limiter"
"Input offset"
"VIOFF"
"Gain"
"K"
"Output upper delta"
"VOUD"
"Output lower delta"
"VOLD"
"Upper and lower smoothing range"
"ULSR"
"Wattmeter"
"Gain"
"K"
"Nonlinear Transformer"
"Primary turns"
"N1"
"Primary resistance"
"R1"
"Primary leakage inductance"
"L1"
"Secondary turns"
"N2"
"Secondary resistance"
"R2"
"Secondary leakage inductance"
"L2"
"Control co-ordinate 5"
"C5"
"Pulse width co-ordinate 5"
"PW5"
"N-Channel GaAsFET"
"Pinch-off voltage"
"VTO"
"Transconductance"
"BETA"
"Doping tail extending parameter"
"B"
"Saturation voltage"
"ALPHA"
"Channel-length modulation"
"LAMBDA"
"Drain ohmic resistance"
"RD"
"Source ohmic resistance"
"RS"
"Zero-bias G-S junction capacitance"
"CGS"
"Zero-bias G-D junction capacitance"
"CGD"
"Gate junction potential"
"PB"
"Flicker noise coefficient"
"KF"
"Flicker noise exponent"
"AF"
"Coefficient for forward-bias depletion capacitance formula"
"FC"
"P-Channel GaAsFET"
"Nonlinear Dependent Source"
"Enter source expression"
"Expression"
"Breakpoint control"
"REL"
"Breakpoint control"
"ABS"
"Buck (Step-Down) Converter"
"Filter inductance"
"L"
"Filter inductor ESR"
"R"
"Switching frequency"
"FS"
"Boost (Step-Up) Converter"
"Field resistance"
"RF"
"Field inductance"
"LF"
"Rated armature current"
"IAN"
"Rated field voltage"
"VFN"
"Load torque"
"TL"
"Triode Vacuum Tube"
"Plate-cathode voltage"
"VPK"
"Grid-cathode voltage"
"VGK"
"Plate current"
"IP"
"Amplification factor"
"u"
"Grid-cathode capacitance"
"CGK"
"Plate-cathode capacitance"
"CPK"
"Grid-plate capacitance"
"CGP"
"Phase-Locked Loop"
"Phase detector conversion gain"
"KD"
"VCO conversion gain"
"KO"
"VCO free running frequency"
"FC"
"Low pass filter pole location"
"FP"
"VCO output amplitude"
"VOM"
"Reference voltage"
"VREF"
"Convergence-aid resistance"
"RCONV"
"Buck-Boost Converter"
"Breakdown resistance"
"RB"
"Reverse current"
"IREV"
"Comparator"
"Gain"
"A"
"Output high level"
"VOH"
"Output low level"
"VOL"
"Low-to-high response time"
"TRR"
"High-to-low response time"
"TRF"
"Rise time"
"TR"
"Fall time"
"TF"
"Magnetic field co-ordinate 6"
"H6"
"Flux density co-ordinate 6"
"B6"
"Magnetic field co-ordinate 7"
"H7"
"Flux density co-ordinate 7"
"B7"
"Magnetic field co-ordinate 8"
"H8"
"Flux density co-ordinate 8"
"B8"
"Magnetic field co-ordinate 9"
"H9"
"Flux density co-ordinate 9"
"B9"
"Magnetic field co-ordinate 10"
"H10"
"Flux density co-ordinate 10"
"B10"
"Magnetic field co-ordinate 11"
"H11"
"Flux density co-ordinate 11"
"B11"
"Magnetic field co-ordinate 12"
"H12"
"Flux density co-ordinate 12"
"B12"
"Magnetic field co-ordinate 13"
"H13"
"Flux density co-ordinate 13"
"B13"
"Magnetic field co-ordinate 14"
"H14"
"Flux density co-ordinate 14"
"B14"
"Magnetic field co-ordinate 15"
"H15"
"Flux density co-ordinate 15"
"B15"
"Input offset voltage"
"VOFFSET"
"Positive supply current"
"ICC+"
"Negative supply current"
"ICC-"
"Maximum positive supply current"
"IMAX+"
"Maximum negative supply current"
"IMAX-"
"Don't limit timestep to less than line delay"
"NOSTEPLIMIT"
"Don't do complex timestep control"
"NOCONTROL"
"Use linear interpolation"
"LININTERP"
"Use linear when quadratic seems bad"
"MIXEDINTERP"
"Use Newton-Raphson method for timestep control"
"TRUNCNR"
"Don't limit timestep to keep impulse-response errors low"
"TRUNCDONTCUT"
"Enable COMPACTREL"
"Special RELTOL for history compaction"
"COMPACTREL"
"Default"
"RELTOL"
"Enable COMPACTABS"
"Special ABSTOL for history compaction"
"COMPACTABS"
"Default"
"ABSTOL"
"Enable TD"
"Enable F and NL"
"Frequency"
"F"
"Normalized electrical length"
"NL"
"Enable initial conditions"
"Port 1 voltage"
"V1"
"Port 1 current"
"I1"
"Port 2 voltage"
"V2"
"Port 2 current"
"I2"
"Source expression"
"7-Terminal Opamp"
"9-Terminal Opamp"
"Netlist Component"
"Select input file~Accept~No input file"
"~in~Text only (*.TXT)|*.txt|Scope Data (*.SCP)|*.scp|~txt"
"Filename"
"Offset"
"VO"
"Transfer Function Error:  At least one of the denominator coefficients must be non-zero."
"Transfer Function Error:  The order of the numerator must be less than or equal to the order of the denominator."
"Vacuum Tube Parameter Error:  The following parameter restrictions must hold\n\nu*VGK+VPK > 0"
"The Mark transmission frequency can not be equal to the Space transmission frequency."
"The piecewise linear source could not open the file:  "
"The filename parameter, for the piecewise linear source, was not specified."
"Textbox"
"Title Block"
$
ewx_hdr          $   analog.msg   &   ì5   6  ¿ªª